# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Service_pb2 as Service__pb2


class DatanodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteData = channel.unary_unary(
                '/DatanodeService/WriteData',
                request_serializer=Service__pb2.WriteRequest.SerializeToString,
                response_deserializer=Service__pb2.WriteResponse.FromString,
                )
        self.ReadData = channel.unary_unary(
                '/DatanodeService/ReadData',
                request_serializer=Service__pb2.ReadRequest.SerializeToString,
                response_deserializer=Service__pb2.ReadResponse.FromString,
                )


class DatanodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatanodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteData': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteData,
                    request_deserializer=Service__pb2.WriteRequest.FromString,
                    response_serializer=Service__pb2.WriteResponse.SerializeToString,
            ),
            'ReadData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadData,
                    request_deserializer=Service__pb2.ReadRequest.FromString,
                    response_serializer=Service__pb2.ReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DatanodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatanodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DatanodeService/WriteData',
            Service__pb2.WriteRequest.SerializeToString,
            Service__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DatanodeService/ReadData',
            Service__pb2.ReadRequest.SerializeToString,
            Service__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
